-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 12:18:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PCParts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PCParts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PCParts` DEFAULT CHARACTER SET utf8 ;
USE `PCParts` ;

-- -----------------------------------------------------
-- Table `PCParts`.`CPU Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`CPU Manufacturer` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`Socket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`Socket` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `CPU Manufacturer_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Socket_CPU Manufacturer1_idx` (`CPU Manufacturer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Socket_CPU Manufacturer1`
    FOREIGN KEY (`CPU Manufacturer_ID`)
    REFERENCES `PCParts`.`CPU Manufacturer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`DDR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`DDR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`CPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`CPU` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `Speed` INT NOT NULL,
  `CoreCount` INT NOT NULL,
  `ThreadCount` INT NOT NULL,
  `TDP` INT NOT NULL,
  `Socket_ID` INT NOT NULL,
  `Socket_CPU Manufacturer_ID` INT NOT NULL,
  `DDR_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_CPU_Socket1_idx` (`Socket_ID` ASC, `Socket_CPU Manufacturer_ID` ASC) VISIBLE,
  INDEX `fk_CPU_DDR1_idx` (`DDR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CPU_Socket1`
    FOREIGN KEY (`Socket_ID` , `Socket_CPU Manufacturer_ID`)
    REFERENCES `PCParts`.`Socket` (`ID` , `CPU Manufacturer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CPU_DDR1`
    FOREIGN KEY (`DDR_ID`)
    REFERENCES `PCParts`.`DDR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`Cooler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`Cooler` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `NoiseLevel` INT NOT NULL,
  `WaterCooled` TINYINT NOT NULL,
  `Fanless` TINYINT NOT NULL,
  `Socket_ID` INT NOT NULL,
  `Socket_CPU Manufacturer_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Cooler_Socket1_idx` (`Socket_ID` ASC, `Socket_CPU Manufacturer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cooler_Socket1`
    FOREIGN KEY (`Socket_ID` , `Socket_CPU Manufacturer_ID`)
    REFERENCES `PCParts`.`Socket` (`ID` , `CPU Manufacturer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`MemorySpeed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`MemorySpeed` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`FormFactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`FormFactor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`Motherboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`Motherboard` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `RamSlots` INT NOT NULL,
  `M.2Slot` TINYINT NOT NULL,
  `DDR_ID` INT NOT NULL,
  `MemorySpeed_ID` INT NOT NULL,
  `FormFactor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Motherboard_DDR1_idx` (`DDR_ID` ASC) VISIBLE,
  INDEX `fk_Motherboard_MemorySpeed1_idx` (`MemorySpeed_ID` ASC) VISIBLE,
  INDEX `fk_Motherboard_FormFactor1_idx` (`FormFactor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Motherboard_DDR1`
    FOREIGN KEY (`DDR_ID`)
    REFERENCES `PCParts`.`DDR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motherboard_MemorySpeed1`
    FOREIGN KEY (`MemorySpeed_ID`)
    REFERENCES `PCParts`.`MemorySpeed` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Motherboard_FormFactor1`
    FOREIGN KEY (`FormFactor_ID`)
    REFERENCES `PCParts`.`FormFactor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`Storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`Storage` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Size` INT NOT NULL,
  `Type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`Memory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`Memory` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `RamSlots` INT NOT NULL,
  `DDR_ID` INT NOT NULL,
  `MemorySpeed_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Memory_DDR1_idx` (`DDR_ID` ASC) VISIBLE,
  INDEX `fk_Memory_MemorySpeed1_idx` (`MemorySpeed_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Memory_DDR1`
    FOREIGN KEY (`DDR_ID`)
    REFERENCES `PCParts`.`DDR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Memory_MemorySpeed1`
    FOREIGN KEY (`MemorySpeed_ID`)
    REFERENCES `PCParts`.`MemorySpeed` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`GPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`GPU` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `CoreClock` INT NOT NULL,
  `MemoryType` VARCHAR(20) NOT NULL,
  `MemorySize` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`Case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`Case` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `FormFactor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Case_FormFactor1_idx` (`FormFactor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Case_FormFactor1`
    FOREIGN KEY (`FormFactor_ID`)
    REFERENCES `PCParts`.`FormFactor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCParts`.`PSU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PCParts`.`PSU` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(40) NOT NULL,
  `Description` TEXT(200) NOT NULL,
  `TDP` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  `FormFactor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_PSU_FormFactor1_idx` (`FormFactor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PSU_FormFactor1`
    FOREIGN KEY (`FormFactor_ID`)
    REFERENCES `PCParts`.`FormFactor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
